server {
    listen 80;
    server_name appinfo.bablaindustries.com;

    root /var/www/appinfo.bablaindustries.com/dist;
    index index.html;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|apk)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Error pages
    error_page 404 /index.html;
}
